### ISSUE TITLE
brunch build error

### ISSUE THREAD

**Issue by tdurand** [nezoomie/brunch-eggs-and-bacon#2] opened 2012-05-14 16:37 UTC
Hi, 

I'm facing an issue when i try to use your skeleton:

```
brunch build
```

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:670:11)
    at Object.afterWrite [as oncomplete] (net.js:503:19)
```

My configuration:

`$ node -v
v0.6.14
$ brunch -v
1.2.1`

Thanks

**Comment by nezoomie** [comment] 2012-05-14 17:15
this works for me:

<pre>
$ brunch new testeggsbacon -s git://github.com/nezoomie/brunch-eggs-and-bacon.git

$ cd testeggsbacon

$ brunch build

14 May 19:11:40 - info: compiled.
</pre>


can you give me more details?

**Comment by tdurand** [comment] 2012-05-14 17:23
Do you have the same version of brunch ? (1.2.1) 

`$ brunch -v
   1.2.1`

**Comment by nezoomie** [comment] 2012-05-14 17:29
yep

perhaps it is a package version issue, because I have not updated them yet for version 1.2.1.

Please try the instructions in http://brunch.readthedocs.org/en/latest/upgrading.html#upgrading-to-1-2 and let me know if it works for you.

**Comment by tdurand** [comment] 2012-05-14 17:37
I've run a npm install at the root of the brunch project but it changes
nothing. All packages seem to be installed.

2012/5/14 nezoomie <
reply@reply.github.com

**Comment by nezoomie** [comment] 2012-05-14 17:39
just committed the new package.json file with the new packages version updated, still work for me.

are you running brunch build from the root of your project?

**Comment by tdurand** [comment] 2012-05-14 17:45
Yep of course.

Weird, still the same issue, i tried the other skeletons of the home page
of brunch.io and it worked.

2012/5/14 nezoomie <
reply@reply.github.com

**Comment by nezoomie** [comment] 2012-05-14 17:50
This is weird indeed.
Could be node version? I'm running 0.6.15.

Can you try also sending me your test project?

**Comment by tdurand** [comment] 2012-05-14 18:06
I was running on 0.6.14 , i've upgraded to v0.6.17 but i'm facing the same
issue.

I don't have any project, i'm just trying to clone and build your skeleton

2012/5/14 nezoomie <
reply@reply.github.com

**Comment by nezoomie** [comment] 2012-05-14 18:09
perfect, create a new project that way, pack it in a .zip and send it to me

**Comment by tdurand** [comment] 2012-05-14 18:14
http://dl.dropbox.com/u/17408251/eggs.zip

**Comment by nezoomie** [comment] 2012-05-14 18:17
ok also I stumbled upon this:

http://stackoverflow.com/questions/8673775/process-nexttick-error-in-node-js

in particular the last comment:

"For anyone else who might stumble here looking for why node pukes this error when they try to issue brunch watch --server, check and make sure you don't have any other servers running using the same port (i.e. in another shell)."

**Comment by nezoomie** [comment] 2012-05-14 18:19
I can build your test-project with no issues. Please check comment above.

**Comment by tdurand** [comment] 2012-05-14 18:22
I've already see this comment, but i'm not even trying to watch --server, i'm just trying to build.. And i don't have another brunch watch server shell open...

Maybe it's a brunch 1.2.1 issue.

**Comment by nezoomie** [comment] 2012-05-14 18:26
Are you running Ubuntu?

https://github.com/brunch/brunch/issues/26

**Comment by tdurand** [comment] 2012-05-14 18:28
No, i'm running on Mac OSX Snow Leopard.

**Comment by nezoomie** [comment] 2012-05-14 18:32
ok, let's see when it crashes.

Try to run: BRUNCH_DEBUG=1 brunch build -o build

then paste here the result

**Comment by tdurand** [comment] 2012-05-14 18:34
``````
14 May 15:33:17 - debug: Initializing fs_utils.SourceFile: { path: '/Users/tdurand/Documents/ProjetGitHub/eggs/node_modules/handlebars-brunch/vendor/handlebars.runtime-1.0.0.beta.6.js',
  isHelper: true,
  isVendor: false }
14 May 15:33:18 - debug: Compiled file 'vendor/scripts/brunch_JavaScriptCompiler_handlebars.runtime-1.0.0.beta.6.js'
14 May 15:33:18 - debug: File '/Users/tdurand/Documents/ProjetGitHub/eggs/config.coffee' received event 'add'
14 May 15:33:18 - debug: File 'package.json' received event 'add'
14 May 15:33:18 - debug: File 'app/application.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/application.js', isHelper: false, isVendor: false }
14 May 15:33:18 - debug: File 'app/initialize.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/initialize.js', isHelper: false, isVendor: false }
14 May 15:33:18 - debug: File 'app/assets/index.html' received event 'add'
14 May 15:33:18 - debug: Compiled file 'app/application.js'
14 May 15:33:18 - debug: Compiled file 'app/initialize.js'
14 May 15:33:18 - debug: File 'vendor/scripts/backbone-0.9.2.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'vendor/scripts/backbone-0.9.2.js',
  isHelper: false,
  isVendor: true }
14 May 15:33:18 - debug: File 'vendor/scripts/backbone-mediator.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'vendor/scripts/backbone-mediator.js',
  isHelper: false,
  isVendor: true }
14 May 15:33:18 - debug: File 'vendor/scripts/console-helper.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'vendor/scripts/console-helper.js',
  isHelper: false,
  isVendor: true }
14 May 15:33:18 - debug: File 'vendor/scripts/jquery-1.7.2.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'vendor/scripts/jquery-1.7.2.js',
  isHelper: false,
  isVendor: true }
14 May 15:33:18 - debug: File 'vendor/scripts/underscore-1.3.1.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'vendor/scripts/underscore-1.3.1.js',
  isHelper: false,
  isVendor: true }
14 May 15:33:18 - debug: File 'app/assets/index.html' received event 'add'
14 May 15:33:18 - debug: File 'app/lib/router.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/lib/router.js', isHelper: false, isVendor: false }
14 May 15:33:18 - debug: File 'app/lib/view_helper.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/lib/view_helper.js',
  isHelper: false,
  isVendor: false }
14 May 15:33:18 - debug: File 'app/models/model.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/models/model.js', isHelper: false, isVendor: false }
14 May 15:33:18 - debug: File 'app/models/collection.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/models/collection.js',
  isHelper: false,
  isVendor: false }
14 May 15:33:18 - debug: File 'app/styles/main.scss' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/styles/main.scss',
  isHelper: false,
  isVendor: false }
14 May 15:33:18 - debug: File 'app/views/home_view.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/views/home_view.js',
  isHelper: false,
  isVendor: false }
14 May 15:33:18 - debug: File 'app/views/view.js' received event 'add'
14 May 15:33:18 - debug: Initializing fs_utils.SourceFile: { path: 'app/views/view.js', isHelper: false, isVendor: false }
14 May 15:33:18 - debug: Compiled file 'vendor/scripts/backbone-mediator.js'
14 May 15:33:18 - debug: Compiled file 'vendor/scripts/console-helper.js'
14 May 15:33:18 - debug: Compiled file 'vendor/scripts/underscore-1.3.1.js'
14 May 15:33:18 - debug: Compiled file 'app/lib/router.js'
14 May 15:33:18 - debug: Compiled file 'vendor/scripts/backbone-0.9.2.js'
14 May 15:33:18 - debug: Compiled file 'app/lib/view_helper.js'
14 May 15:33:18 - debug: Compiled file 'app/models/model.js'
14 May 15:33:18 - debug: File 'app/assets/images/glyphicons-halflings-white.png' received event 'add'
14 May 15:33:18 - debug: File 'app/assets/images/glyphicons-halflings.png' received event 'add'
14 May 15:33:18 - debug: Compiled file 'app/models/collection.js'
14 May 15:33:18 - debug: Compiled file 'app/views/home_view.js'
14 May 15:33:18 - debug: Compiled file 'app/views/view.js'

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:670:11)
    at Object.afterWrite [as oncomplete] (net.js:503:19)```
``````

**Comment by nezoomie** [comment] 2012-05-14 18:39
it seems it's crashing before compiling backbone.mediator.js. In config.coffee try to comment it like this:

<pre>
      order:
        before: [
          'vendor/scripts/console-helper.js',
          'vendor/scripts/jquery-1.7.2.js',
          'vendor/scripts/underscore-1.3.1.js',
          'vendor/scripts/backbone-0.9.2.js'

          #'vendor/scripts/backbone-mediator.js',
</pre>


and try again

**Comment by paulmillr** [comment] 2012-05-14 18:42
I don't think commenting-out scripts will happen. The problem is much deeper.

**Comment by tdurand** [comment] 2012-05-14 18:44
Same log.

**Comment by paulmillr** [comment] 2012-05-14 18:48
Just curious — is building a default project (`brunch new app`) gives you `EPIPE` too?

**Comment by tdurand** [comment] 2012-05-14 18:57
No, it's an issue relative to this skeleton.

It works with the default template and this one as well : https://github.com/paulmillr/brunch-with-chaplin

**Comment by paulmillr** [comment] 2012-05-14 18:59
ಠ_ಠ

**Comment by nezoomie** [comment] 2012-05-14 19:03
yeah, same face as well.

Clueless at the moment. Not a node expert, I don't know exactly when an EPIPE error can be thrown. I'll have a better look later.

**Comment by paulmillr** [comment] 2012-05-14 19:04
It can be an issue with simultaneous write + read. @tdurand does removing `app/assets` helps?

**Comment by tdurand** [comment] 2012-05-14 19:06
Okay, no problem, i was just benchmarking some tools, like brunch, maybe the next release will solve the problem. And is i really want to use it, i can make my own skeleton ;-)

Anyway, thanks for your help.

**Comment by tdurand** [comment] 2012-05-14 19:07
@paulmillr It doesn't help

**Comment by paulmillr** [comment] 2012-05-14 19:18
The only plugin that _brunch with eggs and bacon_ has unlike other skeletons is a Sass plugin. It could be a problem too in my opinion.

a) sass installed on the system sucks or
b) sass plugin somehow sucks

this can be checked by removing its line from `package.json` and removing `node_modules/sass-brunch`

**Comment by tdurand** [comment] 2012-05-14 19:24
Well done, brunch succeed to compile.

**Comment by paulmillr** [comment] 2012-05-14 19:27
I've opened brunch/sass-brunch#5 for this, but because it's very hard to reproduce, not sure how to solve it.

**Comment by tdurand** [comment] 2012-05-14 19:29
Ok, i've renamed the scss file in css but i get this page when watching --server:

```
Cannot GET /
```

**Comment by nezoomie** [comment] 2012-05-14 21:45
wow you succeed isolating the problem! Do you think the os (snow leopard/lion) can make any difference?

@tdurand did you put the assets folder that Paul told you to delete back where it was?

**Closed as completed** 2012-05-14 21:46 UTC

**Comment by paulmillr** [comment] 2012-05-14 22:02
> Do you think the os (snow leopard/lion) can make any difference?

@tdurand 's environment certainly somehow related to this, but I don't think snow leopard is a main problem. I think brunch got more than one Sass + osx 10.6 users.

**Comment by tdurand** [comment] 2012-05-14 22:16
@nezoomie I've forgotten to replace asset, thanks !

@nezoomie @paulmillr The good thing is that i don't need saas ;-). But yep, it's a tricky issue, great job.

**Comment by grumpit** [comment] 2012-05-24 01:38
I can also confirm it's a sass issue - I had this same problem (despite not having another server instance running), OS X Lion 10.7.4, and when I removed the sass-brunch line from package.json, the issue was resolved.

Edit:

FWIW, it may be a coffeescript/sass-brunch version issue:

$ npm ls
package-name@0.0.1 /Users/grumpit/rest/of/path
]snip[
├─┬ sass-brunch@1.1.3 
│ └── coffee-script@1.2.0 
]snip[

$ npm ls -g
/usr/local/lib
├─┬ brunch@1.1.2 
]snip[
├── coffee-script@1.3.3 
└─┬ npm@1.1.21 

$ coffee -v
CoffeeScript version 1.3.3

**Comment by eriwen** [comment] 2012-06-29 21:55
I was able to resolve this problem by using MRI 1.9 instead of JRuby and making sure sass was installed. See discussion on brunch/sass-brunch#5
